# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  RayTracer_config = debug
endif
ifeq ($(config),release)
  RayTracer_config = release
endif

PROJECTS := RayTracer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

RayTracer:
ifneq (,$(RayTracer_config))
	@echo "==== Building RayTracer ($(RayTracer_config)) ===="
	@${MAKE} --no-print-directory -C . -f RayTracer.make config=$(RayTracer_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f RayTracer.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   RayTracer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"